# Generated by Django 5.0.3 on 2024-04-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_custom_entry',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
