# Generated by Django 5.0.3 on 2024-04-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version_control', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=2000)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
