# Generated by Django 5.0.3 on 2024-04-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='django_portfolio_website', unique=True),
            preserve_default=False,
        ),
    ]
