# Generated by Django 5.0.3 on 2024-04-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
